name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker build -f Dockerfile.dev -t visbliss93/docker-react .
    - run: docker run visbliss93/docker-react npm run test -- --coverage
